import {StyleSheet} from 'react-native';
export const useStyles = theme =>
    StyleSheet.create({
        root: {
            width: '100%',
            flex: 1,
        },
        container4: {
            marginTop: 20,
            marginBottom: 0,
            marginLeft: 20,
            marginRight: 20,
            borderTopLeftRadius: 10,
            borderTopRightRadius: 10,
            borderBottomEndRadius: 10,
            borderBottomStartRadius: 10,
            padding: 0,
            borderColor: 'white',
            borderWidth: 1,
        },
        container5: {
            marginTop: 0,
            marginBottom: 0,
            marginLeft: 20,
            marginRight: 20,
            height: 50,
            borderTopLeftRadius: 20,
            borderTopRightRadius: 10,
            borderBottomEndRadius: 10,
            borderBottomStartRadius: 10,
            padding: 0,
            borderColor: 'grey',
            borderWidth: 2,
        },
        gradient: {
            flex: 1,
        },
        aboutContent: {
            flex: 8,
            alignItems: 'center',
            marginLeft: 15,
            marginRight: 15,
        },
        text: {
            fontSize: 15,
            color: '#000',
        },
        container: {
            marginTop: 10,
            marginBottom: 0,
            marginLeft: 20,
            marginRight: 20,
            alignItems: 'center',
            padding: 0,
            borderColor: 'white',
            borderWidth: 0,
        },
        container2: {
            marginTop: 20,
            marginBottom: 0,
            marginLeft: 20,
            marginRight: 20,
            borderTopLeftRadius: 0,
            borderTopRightRadius: 0,
            borderBottomEndRadius: 0,
            borderBottomStartRadius: 0,
            padding: 0,
            borderColor: 'white',
            borderWidth: 0,
        },
        container3: {
            marginBottom: 0,
            marginLeft: 20,
            marginRight: 20,
            borderTopLeftRadius: 0,
            borderTopRightRadius: 0,
            borderBottomEndRadius: 0,
            borderBottomStartRadius: 0,
            padding: 0,
            marginTop: 0,
            borderColor: 'white',
            borderWidth: 0,
        },
        verticleLine: {
            height: '100%',
            width: 1,
            backgroundColor: '#909090',
        },
        yearViewItem: {
            height: 82,
            backgroundColor: '#EBEBEB',
            marginTop: 10,
            marginLeft: 12,
            marginRight: 12,
            borderRadius: 7,
        },
        yearViewCheckList: {
            flexDirection: 'row',
            height: theme.hp('4%'),
            marginLeft: 36,
            marginRight: theme.wp('5%'),
            marginTop: 10,
            justifyContent: 'space-between',
            width: theme.wp('54%'),
            alignSelf: 'flex-end',
        },
        progressContent: {
            position: 'absolute',
            left: 0,
            top: 0,
            bottom: 0,
            borderTopLeftRadius: 7,
            borderBottomLeftRadius: 7,
            borderTopRightRadius: 50,
            borderBottomRightRadius: 50,
        },
        calendarContainer: {
            width: theme.wp('60%'),
            alignSelf: 'flex-end',
            marginRight: theme.wp('3%'),
        },
        dateNumberStyle: {
            fontSize: theme.hp('3.8%'),
            fontWeight: 'bold',
            color: '#8080807f',
        },
        dateNameStyle: {
            fontSize: theme.hp('1.6%'),
            fontWeight: 'bold',
            color: '#8080807f',
            paddingTop: theme.hp('0.5%'),
        },
        highlightDateNameStyle: {
            fontSize: theme.hp('1.6%'),
            fontWeight: 'bold',
            color: 'black',
            paddingTop: theme.hp('0.5%'),
        },
        highlightDateNumberStyle: {
            fontSize: theme.hp('3.8%'),
            fontWeight: 'bold',
            color: 'black',
        },
    });
